import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  loginBar: {
    textAlign: 'center',
    padding: 20,
    borderRadius: 20,
    fontSize: 40,
    fontWeight: 'bold',
  },
  nameBar: {
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    borderColor: '#bbb',
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 10,
    marginBottom: 20,
    width: 200,
  },
  emailBar: {
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    borderColor: '#bbb',
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 10,
    width: 200,
  },
  passwordBar: {
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 20,
    textAlign: 'center',
    justifyContent: 'center',
    borderColor: '#bbb',
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 10,
    width: 200,
  },
  configBar: {
    alignSelf: 'center',
    textAlign: 'center',
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#bbb',
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 10,
    width: 200,
  },
  error: {
    borderColor: 'red',
    borderWidth: 1,
  },
});
